angular.module('app.package')
.service('stixNamespaces',[function(){
	return{
	   "xal":{
		  "uri":"urn:oasis:names:tc:ciq:xal:3"
	   },
	   "xnl":{
		  "uri":"urn:oasis:names:tc:ciq:xnl:3"
	   },
	   "AIS":{
		  "schemaLoc":"http://www.us-cert.gov/sites/default/files/STIX_Namespace/AIS_Bundle_Marking_1.1.1_v1.0.xsd",
		  "uri":"http://www.us-cert.gov/STIXMarkingStructure#AISConsentMarking-2"
	   },
	   "AccountObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Account/2.1/Account_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#AccountObject-2"
	   },
	   "PortObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Port/2.1/Port_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#PortObject-2"
	   },
	   "CodeObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Code/2.1/Code_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#CodeObject-2"
	   },
	   "ttp":{
		  "schemaLoc":"http://stix.mitre.org/XMLSchema/ttp/1.1.1/ttp.xsd",
		  "uri":"http://stix.mitre.org/TTP-1"
	   },
	   "VolumeObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Volume/2.1/Volume_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#VolumeObject-2"
	   },
	   "PDFFileObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/PDF_File/1.1/PDF_File_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#PDFFileObject-1"
	   },
	   "ArchiveFileObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Archive_File/1.0/Archive_File_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#ArchiveFileObject-1"
	   },
	   "indicator":{
		  "schemaLoc":"http://stix.mitre.org/XMLSchema/indicator/2.1.1/indicator.xsd",
		  "uri":"http://stix.mitre.org/Indicator-2"
	   },
	   "DNSCacheObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/DNS_Cache/2.1/DNS_Cache_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#DNSCacheObject-2"
	   },
	   "ProductObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Product/2.1/Product_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#ProductObject-2"
	   },
	   "stixCommon":{
		  "schemaLoc":"http://stix.mitre.org/XMLSchema/common/1.1.1/stix_common.xsd",
		  "uri":"http://stix.mitre.org/common-1"
	   },
	   "WinSystemObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Win_System/2.1/Win_System_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#WinSystemObject-2"
	   },
	   "capec":{
		  "schemaLoc":"http://stix.mitre.org/XMLSchema/extensions/attack_pattern/capec_2.7/1.0.1/capec_2.7_attack_pattern.xsd",
		  "uri":"http://stix.mitre.org/extensions/AP#CAPEC2.7-1"
	   },
	   "X509CertificateObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/X509_Certificate/2.1/X509_Certificate_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#X509CertificateObject-2"
	   },
	   "NetworkRouteObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Network_Route/2.1/Network_Route_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#NetworkRouteObject-2"
	   },
	   "MemoryObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Memory/2.1/Memory_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#MemoryObject-2"
	   },
	   "TOUMarking":{
		  "schemaLoc":"http://stix.mitre.org/XMLSchema/extensions/marking/terms_of_use/1.0.1/terms_of_use_marking.xsd",
		  "uri":"http://data-marking.mitre.org/extensions/MarkingStructure#Terms_Of_Use-1"
	   },
	   "snortTM":{
		  "schemaLoc":"http://stix.mitre.org/XMLSchema/extensions/test_mechanism/snort/1.1.1/snort_test_mechanism.xsd",
		  "uri":"http://stix.mitre.org/extensions/TestMechanism#Snort-1"
	   },
	   "UnixFileObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Unix_File/2.1/Unix_File_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#UnixFileObject-2"
	   },
	   "ProcessObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Process/2.1/Process_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#ProcessObject-2"
	   },
	   "genericTM":{
		  "schemaLoc":"http://stix.mitre.org/XMLSchema/extensions/test_mechanism/generic/1.1.1/generic_test_mechanism.xsd",
		  "uri":"http://stix.mitre.org/extensions/TestMechanism#Generic-1"
	   },
	   "APIObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/API/2.1/API_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#APIObject-2"
	   },
	   "WinSystemRestoreObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Win_System_Restore/2.1/Win_System_Restore_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#WinSystemRestoreObject-2"
	   },
	   "NetworkConnectionObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Network_Connection/2.1/Network_Connection_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#NetworkConnectionObject-2"
	   },
	   "WinComputerAccountObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Win_Computer_Account/2.1/Win_Computer_Account_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#WinComputerAccountObject-2"
	   },
	   "WinPipeObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Win_Pipe/2.1/Win_Pipe_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#WinPipeObject-2"
	   },
	   "WinKernelObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Win_Kernel/2.1/Win_Kernel_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#WinKernelObject-2"
	   },
	   "WinPrefetchObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Win_Prefetch/2.1/Win_Prefetch_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#WinPrefetchObject-2"
	   },
	   "SemaphoreObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Semaphore/2.1/Semaphore_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#SemaphoreObject-2"
	   },
	   "CustomObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Custom/1.1/Custom_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#CustomObject-1"
	   },
	   "WinCriticalSectionObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Win_Critical_Section/2.1/Win_Critical_Section_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#WinCriticalSectionObject-2"
	   },
	   "DNSRecordObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/DNS_Record/2.1/DNS_Record_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#DNSRecordObject-2"
	   },
	   "UserAccountObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/User_Account/2.1/User_Account_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#UserAccountObject-2"
	   },
	   "stixVocabs":{
		  "schemaLoc":"http://stix.mitre.org/XMLSchema/default_vocabularies/1.1.1/stix_default_vocabularies.xsd",
		  "uri":"http://stix.mitre.org/default_vocabularies-1"
	   },
	   "ioc-tr":{
		  "schemaLoc":"http://schemas.mandiant.com/2010/ioc/TR/ioc-TR.xsd",
		  "uri":"http://schemas.mandiant.com/2010/ioc/TR/"
	   },
	   "DNSQueryObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/DNS_Query/2.1/DNS_Query_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#DNSQueryObject-2"
	   },
	   "FileObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/File/2.1/File_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#FileObject-2"
	   },
	   "et":{
		  "schemaLoc":"http://stix.mitre.org/XMLSchema/exploit_target/1.1.1/exploit_target.xsd",
		  "uri":"http://stix.mitre.org/ExploitTarget-1"
	   },
	   "AddressObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Address/2.1/Address_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#AddressObject-2"
	   },
	   "NetworkRouteEntryObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Network_Route_Entry/2.1/Network_Route_Entry_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#NetworkRouteEntryObject-2"
	   },
	   "SocketAddressObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Socket_Address/1.1/Socket_Address_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#SocketAddressObject-1"
	   },
	   "tlpMarking":{
		  "schemaLoc":"http://stix.mitre.org/XMLSchema/extensions/marking/tlp/1.1.1/tlp_marking.xsd",
		  "uri":"http://data-marking.mitre.org/extensions/MarkingStructure#TLP-1"
	   },
	   "UnixProcessObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Unix_Process/2.1/Unix_Process_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#UnixProcessObject-2"
	   },
	   "GUIWindowObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/GUI_Window/2.1/GUI_Window_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#GUIWindowObject-2"
	   },
	   "WinFileObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Win_File/2.1/Win_File_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#WinFileObject-2"
	   },
	   "HTTPSessionObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/HTTP_Session/2.1/HTTP_Session_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#HTTPSessionObject-2"
	   },
	   "URIObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/URI/2.1/URI_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#URIObject-2"
	   },
	   "WinExecutableFileObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Win_Executable_File/2.1/Win_Executable_File_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#WinExecutableFileObject-2"
	   },
	   "WhoisObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Whois/2.1/Whois_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#WhoisObject-2"
	   },
	   "incident":{
		  "schemaLoc":"http://stix.mitre.org/XMLSchema/incident/1.1.1/incident.xsd",
		  "uri":"http://stix.mitre.org/Incident-1"
	   },
	   "NetworkPacketObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Network_Packet/2.1/Network_Packet_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#PacketObject-2"
	   },
	   "threat_actor":{
		  "schemaLoc":"http://stix.mitre.org/XMLSchema/threat_actor/1.1.1/threat_actor.xsd",
		  "uri":"http://stix.mitre.org/ThreatActor-1"
	   },
	   "WinFilemappingObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Win_Filemapping/1.0/Win_Filemapping_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#WinFilemappingObject-1"
	   },
	   "WinHandleObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Win_Handle/2.1/Win_Handle_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#WinHandleObject-2"
	   },
	   "LinuxPackageObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Linux_Package/2.1/Linux_Package_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#LinuxPackageObject-2"
	   },
	   "coa":{
		  "schemaLoc":"http://stix.mitre.org/XMLSchema/course_of_action/1.1.1/course_of_action.xsd",
		  "uri":"http://stix.mitre.org/CourseOfAction-1"
	   },
	   "stix-ciqaddress":{
		  "schemaLoc":"http://stix.mitre.org/XMLSchema/extensions/address/ciq_3.0/1.1.1/ciq_3.0_address.xsd",
		  "uri":"http://stix.mitre.org/extensions/Address#CIQAddress3.0-1"
	   },
	   "cybox":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/core/2.1/cybox_core.xsd",
		  "uri":"http://cybox.mitre.org/cybox-2"
	   },
	   "genericStructuredCOA":{
		  "schemaLoc":"http://stix.mitre.org/XMLSchema/extensions/structured_coa/generic/1.1.1/generic_structured_coa.xsd",
		  "uri":"http://stix.mitre.org/extensions/StructuredCOA#Generic-1"
	   },
	   "WinRegistryKeyObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Win_Registry_Key/2.1/Win_Registry_Key_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#WinRegistryKeyObject-2"
	   },
	   "WinMutexObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Win_Mutex/2.1/Win_Mutex_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#WinMutexObject-2"
	   },
	   "campaign":{
		  "schemaLoc":"http://stix.mitre.org/XMLSchema/campaign/1.1.1/campaign.xsd",
		  "uri":"http://stix.mitre.org/Campaign-1"
	   },
	   "UnixPipeObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Unix_Pipe/2.1/Unix_Pipe_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#UnixPipeObject-2"
	   },
	   "UnixUserAccountObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Unix_User_Account/2.1/Unix_User_Account_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#UnixUserAccountObject-2"
	   },
	   "UserSessionObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/User_Session/2.1/User_Session_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#UserSessionObject-2"
	   },
	   "LibraryObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Library/2.1/Library_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#LibraryObject-2"
	   },
	   "simpleMarking":{
		  "schemaLoc":"http://stix.mitre.org/XMLSchema/extensions/marking/simple/1.1.1/simple_marking.xsd",
		  "uri":"http://data-marking.mitre.org/extensions/MarkingStructure#Simple-1"
	   },
	   "DiskPartitionObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Disk_Partition/2.1/Disk_Partition_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#DiskPartitionObject-2"
	   },
	   "WinThreadObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Win_Thread/2.1/Win_Thread_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#WinThreadObject-2"
	   },
	   "DomainNameObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Domain_Name/1.0/Domain_Name_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#DomainNameObject-1"
	   },
	   "GUIDialogboxObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/GUI_Dialogbox/2.1/GUI_Dialogbox_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#GUIDialogboxObject-2"
	   },
	   "HostnameObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Hostname/1.0/Hostname_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#HostnameObject-1"
	   },
	   "WinProcessObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Win_Process/2.1/Win_Process_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#WinProcessObject-2"
	   },
	   "UnixVolumeObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Unix_Volume/2.1/Unix_Volume_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#UnixVolumeObject-2"
	   },
	   "WinHookObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Win_Hook/1.0/Win_Hook_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#WinHookObject-1"
	   },
	   "MutexObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Mutex/2.1/Mutex_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#MutexObject-2"
	   },
	   "stix-maec":{
		  "schemaLoc":"http://stix.mitre.org/XMLSchema/extensions/malware/maec_4.1/1.0.1/maec_4.1_malware.xsd",
		  "uri":"http://stix.mitre.org/extensions/Malware#MAEC4.1-1"
	   },
	   "WinEventObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Win_Event/2.1/Win_Event_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#WinEventObject-2"
	   },
	   "WinKernelHookObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Win_Kernel_Hook/2.1/Win_Kernel_Hook_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#WinKernelHookObject-2"
	   },
	   "xpil":{
		  "schemaLoc":"http://stix.mitre.org/XMLSchema/external/oasis_ciq_3.0/xPIL.xsd",
		  "uri":"urn:oasis:names:tc:ciq:xpil:3"
	   },
	   "WinTaskObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Win_Task/2.1/Win_Task_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#WinTaskObject-2"
	   },
	   "EmailMessageObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Email_Message/2.1/Email_Message_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#EmailMessageObject-2"
	   },
	   "DeviceObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Device/2.1/Device_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#DeviceObject-2"
	   },
	   "SystemObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/System/2.1/System_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#SystemObject-2"
	   },
	   "LinkObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Link/1.1/Link_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#LinkObject-1"
	   },
	   "WinMemoryPageRegionObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Win_Memory_Page_Region/2.1/Win_Memory_Page_Region_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#WinMemoryPageRegionObject-2"
	   },
	   "WinNetworkRouteEntryObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Win_Network_Route_Entry/2.1/Win_Network_Route_Entry_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#WinNetworkRouteEntryObject-2"
	   },
	   "DiskObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Disk/2.1/Disk_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#DiskObject-2"
	   },
	   "ASObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/AS/1.0/AS_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#ASObject-1"
	   },
	   "WinDriverObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Win_Driver/3.0/Win_Driver_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#WinDriverObject-3"
	   },
	   "GUIObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/GUI/2.1/GUI_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#GUIObject-2"
	   },
	   "cyboxCommon":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/common/2.1/cybox_common.xsd",
		  "uri":"http://cybox.mitre.org/common-2"
	   },
	   "ImageFileObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Image_File/1.0/Image_File_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#ImageFileObject-1"
	   },
	   "WinWaitableTimerObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Win_Waitable_Timer/2.1/Win_Waitable_Timer_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#WinWaitableTimerObject-2"
	   },
	   "WinNetworkShareObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Win_Network_Share/2.1/Win_Network_Share_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#WinNetworkShareObject-2"
	   },
	   "WinVolumeObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Win_Volume/2.1/Win_Volume_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#WinVolumeObject-2"
	   },
	   "PipeObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Pipe/2.1/Pipe_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#PipeObject-2"
	   },
	   "ArtifactObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Artifact/2.1/Artifact_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#ArtifactObject-2"
	   },
	   "marking":{
		  "schemaLoc":"http://stix.mitre.org/XMLSchema/data_marking/1.1.1/data_marking.xsd",
		  "uri":"http://data-marking.mitre.org/Marking-1"
	   },
	   "stix-ciq":{
		  "schemaLoc":"http://stix.mitre.org/XMLSchema/extensions/identity/ciq_3.0/1.1.1/ciq_3.0_identity.xsd",
		  "uri":"http://stix.mitre.org/extensions/Identity#CIQIdentity3.0-1"
	   },
	   "WinServiceObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Win_Service/2.1/Win_Service_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#WinServiceObject-2"
	   },
	   "stix":{
		  "schemaLoc":"http://stix.mitre.org/XMLSchema/core/1.1.1/stix_core.xsd",
		  "uri":"http://stix.mitre.org/stix-1"
	   },
	   "yaraTM":{
		  "schemaLoc":"http://stix.mitre.org/XMLSchema/extensions/test_mechanism/yara/1.1.1/yara_test_mechanism.xsd",
		  "uri":"http://stix.mitre.org/extensions/TestMechanism#YARA-1"
	   },
	   "WinMailslotObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Win_Mailslot/2.1/Win_Mailslot_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#WinMailslotObject-2"
	   },
	   "UnixNetworkRouteEntryObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Unix_Network_Route_Entry/2.1/Unix_Network_Route_Entry_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#UnixNetworkRouteEntryObject-2"
	   },
	   "NetworkFlowObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Network_Flow/2.1/Network_Flow_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#NetworkFlowObject-2"
	   },
	   "NetworkSubnetObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Network_Subnet/2.1/Network_Subnet_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#NetworkSubnetObject-2"
	   },
	   "SMSMessageObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/SMS_Message/1.0/SMS_Message_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#SMSMessageObject-1"
	   },
	   "WinEventLogObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Win_Event_Log/2.1/Win_Event_Log_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#WinEventLogObject-2"
	   },
	   "ioc":{
		  "schemaLoc":"http://schemas.mandiant.com/2010/ioc/ioc.xsd",
		  "uri":"http://schemas.mandiant.com/2010/ioc"
	   },
	   "cyboxVocabs":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/default_vocabularies/2.1/cybox_default_vocabularies.xsd",
		  "uri":"http://cybox.mitre.org/default_vocabularies-2"
	   },
	   "ARPCacheObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/ARP_Cache/1.0/ARP_Cache_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#ARPCacheObject-1"
	   },
	   "NetworkSocketObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Network_Socket/2.1/Network_Socket_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#NetworkSocketObject-2"
	   },
	   "URLHistoryObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/URL_History/1.0/URL_History_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#URLHistoryObject-1"
	   },
	   "WinUserAccountObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Win_User_Account/2.1/Win_User_Account_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#WinUserAccountObject-2"
	   },
	   "WinSemaphoreObj":{
		  "schemaLoc":"http://cybox.mitre.org/XMLSchema/objects/Win_Semaphore/2.1/Win_Semaphore_Object.xsd",
		  "uri":"http://cybox.mitre.org/objects#WinSemaphoreObject-2"
	   },
	   "stix-cvrf":{
		  "schemaLoc":"http://stix.mitre.org/XMLSchema/extensions/vulnerability/cvrf_1.1/1.1.1/cvrf_1.1_vulnerability.xsd",
		  "uri":"http://stix.mitre.org/extensions/Vulnerability#CVRF-1"
	   }
	};
}]);